### ISSUE TITLE
An error was encountered while running the program

### ISSUE THREAD

**Issue by huigeopencv** [mit-wu-lab/automatic_vehicular_control#1]
When I was learning the code, I encountered some problems, including environment configuration and code debugging. I currently configure it exactly as Readme. But there is still a bug that has been bothering me for a long time and has not been solved yet.When I run the main function of a scenario, u.py will generate an error, as shown in the figure.
![Screenshot from 2022-11-07 15-43-20](https://user-images.githubusercontent.com/50897297/200330085-ead7d510-7703-48f4-baf0-dd56ab4858cb.png)

**Comment by ZhongxiaYan** [comment]
Should be easy to fix. Just make `terminal_width` return a constant int (e.g. 80). It doesn't matter
